#+title:  hatsuon.el
#+property: LOGGING nil

Add the English pronunciation functionality to Emacs.

* Contents :noexport:
:PROPERTIES:
:TOC:      :include siblings
:END:
:CONTENTS:
- [[#installation][Installation]]
- [[#usage][Usage]]
- [[#changelog][Changelog]]
- [[#development][Development]]
- [[#license][License]]
:END:

* Installation
:PROPERTIES:
:TOC:      :depth 0
:END:
** MELPA

This package is not on MELPA.

** Manual

Install the required packages:

- ~emms~
- ~request~
- ~s~

Then place ~hatsuon.el~ in your ~load-path~, and put the following line in your ~init.el~ file:

#+begin_src elisp
  (require 'hatsuon)
#+end_src

Or using ~use-package~ with ~straight~:

#+begin_src elisp
  (use-package hatsuon
    :straight (:host github :repo "okomestudio/hatsuon.el"))
#+end_src

By default, ~hatsuon.el~ pull audio from Wiktionary. To use audio from other sites, load their audio URL getter extension:

#+begin_src elisp
  (use-package hatsuon
     :straight (:host github :repo "okomestudio/hatsuon.el"
                      :files (:defaults "extensions/*"))
     :custom (hatsuon-audio-url-getters '(hatsuon-mw-audio-url-getter))
     :config
     (require 'hatsuon-mw))
#+end_src

* Usage
:PROPERTIES:
:TOC:      :depth 0
:END:

- ~hatsuon-play-audio~: Play the audio for the word
- ~hatsuon-remove-cached-audio-file~: Remove an audio file cached locally

* Changelog
:PROPERTIES:
:TOC:      :depth 0
:END:
** 0.1

Add external audio getters as extensions.

** Alpha

Initial release.

* Development

TBD.

# Local Variables:
# eval: (require 'org-make-toc)
# before-save-hook: org-make-toc
# org-export-with-properties: ()
# org-export-with-title: t
# End:
